using System;
using System.Runtime.InteropServices;
using DashCapture.Core.Configuration;
using DashCapture.Core.Models;
using DashCapture.Native;

namespace DashCapture.Storage;

public sealed class TdmsCaptureWriter : IDisposable
{
    private readonly StorageSettings _settings;
    private readonly IReadOnlyList<DeviceDescriptor> _devices;
    private readonly Dictionary<int, IntPtr> _groups = new();
    private readonly Dictionary<ChannelKey, IntPtr> _channels = new();
    private readonly DateTimeOffset _startedAt = DateTimeOffset.Now;
    private IntPtr _file;
    private int _fileIndex;
    private string _currentPath = string.Empty;

    public TdmsCaptureWriter(StorageSettings settings, IReadOnlyList<DeviceDescriptor> devices)
    {
        _settings = settings;
        _devices = devices;
        NativeBootstrap.AddSearchDirectory(settings.TdmRuntimeDir);
        Directory.CreateDirectory(settings.RootPath);
        OpenNextFile();
    }

    public string CurrentPath => _currentPath;

    public void AppendBlock(Core.Memory.AcquisitionBlock block)
    {
        if (_file == IntPtr.Zero)
        {
            return;
        }

        DeviceDescriptor? device = ResolveDevice(block.Header);
        if (device is null || device.Channels.Count == 0)
        {
            return;
        }

        int sampleCount = block.Header.DataCountPerChannel;
        int channelCount = Math.Max(1, block.ChannelCount);
        float[] scratch = new float[sampleCount];

        foreach (ChannelDescriptor channel in device.Channels)
        {
            if (channel.DataIndex < 0 || channel.DataIndex >= channelCount)
            {
                continue;
            }

            NativeDeinterleaver.CopyFloatChannel(block.DataPointer, sampleCount, channelCount, channel.DataIndex, scratch);
            AppendChannel(channel, scratch.AsSpan(0, sampleCount));
        }

        RollFileIfNeeded();
    }

    public void Save()
    {
        if (_file != IntPtr.Zero)
        {
            TdmNative.ThrowIfError(TdmNative.DDC_SaveFile(_file), "DDC_SaveFile");
        }
    }

    public void Dispose()
    {
        if (_file != IntPtr.Zero)
        {
            try
            {
                TdmNative.DDC_SaveFile(_file);
            }
            finally
            {
                TdmNative.DDC_CloseFile(_file);
                _file = IntPtr.Zero;
            }
        }
    }

    private void AppendChannel(ChannelDescriptor channel, ReadOnlySpan<float> values)
    {
        if (!_channels.TryGetValue(new ChannelKey(channel.DeviceId, channel.ChannelId), out IntPtr handle))
        {
            return;
        }

        unsafe
        {
            fixed (float* ptr = values)
            {
                TdmNative.ThrowIfError(
                    TdmNative.DDC_AppendDataValues(handle, new IntPtr(ptr), (UIntPtr)values.Length),
                    "DDC_AppendDataValues");
            }
        }
    }

    private void OpenNextFile()
    {
        DisposeCurrentFile();
        _groups.Clear();
        _channels.Clear();

        _fileIndex++;
        _currentPath = CreateNextFilePath();

        TdmNative.ThrowIfError(
            TdmNative.DDC_CreateFile(
                _currentPath,
                TdmNative.TdmsFileType,
                $"DASH Capture {_startedAt:yyyy-MM-dd HH:mm:ss}",
                "Raw callback data captured from DASH SDK. Metadata sidecar is generated by the application.",
                "DASH Capture",
                Environment.UserName,
                out _file),
            "DDC_CreateFile");

        foreach (DeviceDescriptor device in _devices)
        {
            string groupName = $"Device_{device.DeviceId + 1:0000}_{Sanitize(device.IpAddress)}";
            string description = $"DeviceId={device.DeviceId}; Ip={device.IpAddress}; SampleRate={device.SampleRate}";
            TdmNative.ThrowIfError(TdmNative.DDC_AddChannelGroup(_file, groupName, description, out IntPtr group), "DDC_AddChannelGroup");
            _groups[device.DeviceId] = group;

            foreach (ChannelDescriptor channel in device.Channels)
            {
                string channelName = $"AI{channel.ChannelId + 1:000}";
                string channelDescription = $"DeviceId={channel.DeviceId}; ChannelId={channel.ChannelId}; DataIndex={channel.DataIndex}; RawType=float32";
                TdmNative.ThrowIfError(
                    TdmNative.DDC_AddChannel(group, DdcDataType.Float, channelName, channelDescription, channel.Unit, out IntPtr channelHandle),
                    "DDC_AddChannel");
                _channels[new ChannelKey(channel.DeviceId, channel.ChannelId)] = channelHandle;
            }
        }
    }

    private void RollFileIfNeeded()
    {
        long splitBytes = Math.Max(1L, _settings.FileSplitGb) * 1024L * 1024L * 1024L;
        if (!string.IsNullOrEmpty(_currentPath) && File.Exists(_currentPath) && new FileInfo(_currentPath).Length >= splitBytes)
        {
            OpenNextFile();
        }
    }

    private DeviceDescriptor? ResolveDevice(Core.Models.SdkSampleData header)
    {
        return _devices.FirstOrDefault(d => d.DeviceId == header.GroupId) ??
               _devices.FirstOrDefault(d => d.DeviceId == header.MachineId);
    }

    private string CreateNextFilePath()
    {
        string stem = _settings.NamingMode == FileNamingMode.Custom
            ? Sanitize(string.IsNullOrWhiteSpace(_settings.CustomFileName) ? "DashCapture" : _settings.CustomFileName.Trim())
            : $"DashCapture_{_startedAt:yyyyMMdd_HHmmss}";

        if (_settings.NamingMode == FileNamingMode.Time)
        {
            return CreateUniquePath(stem, startSuffix: _fileIndex, allowBare: false);
        }

        return CreateUniquePath(stem, startSuffix: 1, allowBare: _fileIndex == 1);
    }

    private string CreateUniquePath(string stem, int startSuffix, bool allowBare)
    {
        if (allowBare)
        {
            string bare = Path.Combine(_settings.RootPath, $"{stem}.tdms");
            if (!File.Exists(bare))
            {
                return bare;
            }
        }

        int suffix = Math.Max(1, startSuffix);
        while (true)
        {
            string candidate = Path.Combine(_settings.RootPath, $"{stem}_{suffix:000}.tdms");
            if (!File.Exists(candidate))
            {
                return candidate;
            }

            suffix++;
        }
    }

    private void DisposeCurrentFile()
    {
        if (_file == IntPtr.Zero)
        {
            return;
        }

        TdmNative.DDC_SaveFile(_file);
        TdmNative.DDC_CloseFile(_file);
        _file = IntPtr.Zero;
    }

    private static string Sanitize(string value)
    {
        foreach (char invalid in Path.GetInvalidFileNameChars())
        {
            value = value.Replace(invalid, '_');
        }

        return value.Replace('.', '_').Replace(':', '_');
    }
}
