<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>$(DashCaptureTargetFrameworks)</TargetFrameworks>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\DashCapture.Analysis\DashCapture.Analysis.csproj" />
    <ProjectReference Include="..\..\src\DashCapture.Storage\DashCapture.Storage.csproj" />
  </ItemGroup>
</Project>
